# Generated by Django 3.2.7 on 2021-09-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0002_auto_20210929_1605"),
    ]

    operations = []
