# Generated by Django 3.2.7 on 2021-09-29 11:08

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("owners", "0003_auto_20210929_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="owner",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AddField(
            model_name="owner", name="description", field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name="owner", name="phone", field=models.CharField(max_length=20)
        ),
        migrations.AddField(
            model_name="owner", name="is_mvp", field=models.BooleanField(default=False)
        ),
        migrations.AddField(
            model_name="owner",
            name="hire_date",
            field=models.DateTimeField(default=datetime.now, blank=True),
        ),
    ]
