# Generated by Django 3.2.7 on 2021-09-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0005_auto_20210929_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
    ]
