# Generated by Django 2.2.13 on 2021-09-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostel",
            old_name="state",
            new_name="Nearby_University",
        ),
    ]
