# Generated by Django 2.2.13 on 2021-09-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0002_auto_20210916_0714"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostel",
            old_name="bedrooms",
            new_name="seater",
        ),
    ]
