# Generated by Django 2.2.13 on 2021-09-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0003_auto_20210916_0717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="garage",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=100
            ),
        ),
    ]
