# Generated by Django 2.2.13 on 2021-09-16 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0004_auto_20210916_0759"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostel",
            old_name="garage",
            new_name="For",
        ),
    ]
