# Generated by Django 2.2.13 on 2021-09-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0005_auto_20210916_0801"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostel",
            name="lot_size",
        ),
        migrations.RemoveField(
            model_name="hostel",
            name="sqft",
        ),
        migrations.AddField(
            model_name="hostel",
            name="Food_facility",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="Yes", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="laundary_facility",
            field=models.CharField(
                choices=[("Y", "Yes"), ("N", "No")], default="Yes", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="hostel",
            name="For",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default="Male", max_length=100
            ),
        ),
    ]
