# Generated by Django 2.2.13 on 2021-09-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0007_auto_20210917_0618"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostel",
            old_name="For",
            new_name="hostel_type",
        ),
    ]
