# Generated by Django 2.2.13 on 2021-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0009_auto_20210917_0630"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="bathrooms",
            field=models.IntegerField(),
        ),
    ]
