# Generated by Django 2.2.13 on 2021-09-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0010_auto_20210917_0634"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="internet_facility",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")], default="Yes", max_length=100
            ),
        ),
    ]
