# Generated by Django 3.2.7 on 2021-09-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0011_listing_internet_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyUniversities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='Nearby_University',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='food_facility',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='internet_facility',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='laundary_facility',
        ),
        migrations.AddField(
            model_name='hostel',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='locaation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hostel',
            name='nearby_universities',
            field=models.ManyToManyField(to='hostels.NearbyUniversities'),
        ),
    ]
