# Generated by Django 3.2.7 on 2021-09-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0012_auto_20210928_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostel',
            old_name='locaation',
            new_name='location',
        ),
    ]
