# Generated by Django 3.2.7 on 2021-09-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0013_rename_locaation_hostel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='utilities',
            field=models.ManyToManyField(to='hostels.Utilities'),
        ),
    ]
