# Generated by Django 3.2.7 on 2021-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0014_hostel_utilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='nearby_universities',
            field=models.ManyToManyField(null=True, to='hostels.NearbyUniversities'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='utilities',
            field=models.ManyToManyField(null=True, to='hostels.Utilities'),
        ),
    ]
