# Generated by Django 3.2.7 on 2021-09-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0015_auto_20210929_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='nearby_universities',
            field=models.ManyToManyField(blank=True, null=True, to='hostels.NearbyUniversities'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='utilities',
            field=models.ManyToManyField(blank=True, null=True, to='hostels.Utilities'),
        ),
    ]
